import {Header,Footer,Btn,SearchBar,PropertyCard,HotelCard,PlanCards,MembershipGuide,PointsGuide,SecurityGuide} from '@/components/ui';
import {properties,hotels,destinations,flightRoutes} from '@/lib/data';
import {HomeFilters} from '@/components/home-filters';
const steps=[['1','Publicá tu casa','Mostrá tu lugar, definí disponibilidad y empezá a sumar puntos.'],['2','Elegí tu destino','Usá tus puntos para alojarte en casas de otros miembros.'],['3','Viajá con ventajas','Accedé a hoteles aliados con beneficios exclusivos para la comunidad.']];
const program=[['01','Activá tu membresía','Con el Plan Viajero publicás tu casa, accedés a intercambios y recibís 3 puntos de bienvenida.'],['02','Ganás puntos por alojar','Cada noche vale puntos según la demanda: 0,5 en baja, 1 en media y 2 en alta temporada.'],['03','Canjeás por experiencias','Usalos para alojarte en casas de otros miembros. Los puntos vencen al año y no se transfieren.']];
export default function Home(){return <><Header/><main>
<section className="hero"><div className="wrap hero-copy"><span className="eyebrow">Tu próxima aventura empieza acá</span><h1>Viajá más,<br/>gastá menos.</h1><p>Intercambiá tu casa, conocé destinos increíbles y accedé a beneficios exclusivos en hoteles de Latinoamérica.</p><div className="actions"><Btn href="/register">Empezar gratis</Btn><Btn href="/hotels" outline>Ver hoteles</Btn></div><SearchBar/></div></section>
<HomeFilters/>
<section className="wrap section"><div className="sectionhead"><div><h2>Curated properties</h2><p>Casas genuinas para vivir cada destino desde adentro.</p></div><Btn href="/properties" outline>Ver todas</Btn></div><div className="grid">{properties.map(x=><PropertyCard item={x} key={x.id}/>)}</div></section>
<section className="wrap section destinations-section"><div className="destinations"><div className="sectionhead"><div><h2>Elegí tu próxima historia</h2><p>Destinos seleccionados para vivirlos como local.</p></div></div><div className="destination-grid">{destinations.map(x=><article className="destination" key={x.id}><img src={x.image} alt={`${x.name}, ${x.description}`}/><div><strong>{x.name}</strong><span>{x.description}</span></div></article>)}</div></div></section>
<section className="how"><div className="wrap section"><div className="sectionhead"><div><h2>Así de fácil</h2><p>Una comunidad hecha para viajar en serio.</p></div></div><div className="steps">{steps.map(x=><article key={x[0]}><div className="number">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section className="membership-explainer"><div className="wrap section"><div className="sectionhead"><div><span className="eyebrow">Tu membresía, en simple</span><h2>Cómo funciona Troca</h2><p>Una forma flexible de alojarte, compartir y aprovechar cada viaje.</p></div><Btn href="/register/plan" outline>Ver membresías</Btn></div><div className="program-grid">{program.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="program-note"><b>¿No tenés casa?</b> Con el Plan Base podés acceder a hoteles aliados y beneficios exclusivos de viaje.</div></div></section>
<section className="wrap section"><div className="saving"><div><span className="eyebrow" style={{color:'#dfcda9'}}>La cuenta es simple</span><h2>Tu membresía se paga sola.</h2></div><div><div className="big">Una noche con beneficio Troca puede amortizar toda tu membresía.</div><p>30 días de prueba gratis · Precios y beneficios disponibles al registrarte.</p></div></div></section>
<section className="wrap section"><div className="sectionhead"><div><h2>Hoteles con beneficios reales</h2><p>Diseñados para que cada escapada rinda más.</p></div><Btn href="/hotels" outline>Ver hoteles</Btn></div><div className="grid">{hotels.map(x=><HotelCard item={x} key={x.id}/>)}</div></section>
<section className="flight-section"><div className="wrap section"><div className="sectionhead"><div><span className="eyebrow">Beneficio Premium</span><h2>Vuelos para llegar más lejos</h2><p>Descuentos exclusivos en rutas seleccionadas para miembros Premium.</p></div><Btn href="/register/plan" outline>Conocer Premium</Btn></div><div className="flight-grid">{flightRoutes.map(x=><article className="flight-card" key={`${x[2]}-${x[3]}`}><span className="flight-badge">{x[5]}</span><div className="flight-route"><div><b>{x[2]}</b><small>{x[0]}</small></div><strong>→</strong><div><b>{x[3]}</b><small>{x[1]}</small></div></div><p>✈ {x[4]} · Beneficio para Plan Premium</p></article>)}</div><div className="flight-note">Los descuentos y la disponibilidad se confirman al solicitar la cotización. Próximamente, reserva integrada.</div></div></section>
<section className="wrap section"><div className="sectionhead"><div><h2>Elegí cómo querés viajar</h2><p>30 días gratis para empezar, sin tarjeta. El plan anual ofrece un ahorro claro frente al pago mes a mes.</p></div></div><PlanCards/><div className="plan-guide-wrap"><h2>Tu membresía, paso a paso</h2><MembershipGuide/></div></section>
<section className="points-section"><div className="wrap section"><PointsGuide/></div></section>
<section className="wrap section"><SecurityGuide/></section>
</main><Footer/></>}
