import {Header,Footer,Btn,SearchBar,PropertyCard,HotelCard,PlanCards,MembershipGuide,PointsGuide,SecurityGuide} from '@/components/ui';
import {properties,hotels,destinations,flightRoutes} from '@/lib/data';
import {HomeFilters} from '@/components/home-filters';
import {Localized} from '@/components/localized';
import {Home as HomeIcon, MapPinned, Sparkles} from 'lucide-react';
import {Quote} from 'lucide-react';
const steps=[{number:'1',title:'Publicá tu casa',text:'Mostrá tu lugar, definí disponibilidad y empezá a sumar puntos.',Icon:HomeIcon},{number:'2',title:'Elegí tu destino',text:'Usá tus puntos para alojarte en casas de otros miembros.',Icon:MapPinned},{number:'3',title:'Viajá con ventajas',text:'Accedé a hoteles aliados con beneficios exclusivos para la comunidad.',Icon:Sparkles}];
const program=[['01','Activá tu membresía','Con el Plan Viajero publicás tu casa, accedés a intercambios y recibís 3 puntos de bienvenida.'],['02','Ganás puntos por alojar','Cada noche vale puntos según la demanda: 0,5 en baja, 1 en media y 2 en alta temporada.'],['03','Canjeás por experiencias','Usalos para alojarte en casas de otros miembros. Los puntos vencen al año y no se transfieren.']];
export default function Home(){return <><Header/><main>
<section className="hero hero-immersive"><div className="wrap hero-copy"><span className="eyebrow"><Localized es="Tu próxima aventura empieza acá" pt="Sua próxima aventura começa aqui"/></span><h1><Localized es="Intercambiá casas. Viví el mundo." pt="Troque casas. Viva o mundo."/></h1><p><Localized es="Descubrí hogares únicos y viví cada destino como alguien local." pt="Descubra casas únicas e viva cada destino como alguém local."/></p><SearchBar/></div></section>
<HomeFilters/>
<section className="wrap section"><div className="sectionhead"><div><h2><Localized es="Casas seleccionadas" pt="Casas selecionadas"/></h2><p><Localized es="Casas genuinas para vivir cada destino desde adentro." pt="Casas reais para viver cada destino por dentro."/></p></div><Btn href="/properties" outline><Localized es="Ver todas" pt="Ver todas"/></Btn></div><div className="grid">{properties.map(x=><PropertyCard item={x} key={x.id}/>)}</div></section>
<section className="wrap section destinations-section"><div className="destinations"><div className="sectionhead"><div><h2><Localized es="Elegí tu próxima historia" pt="Escolha sua próxima história"/></h2><p><Localized es="Destinos seleccionados para vivirlos como local." pt="Destinos selecionados para viver como alguém local."/></p></div></div><div className="destination-grid">{destinations.map(x=><article className="destination" key={x.id}><img src={x.image} alt={`${x.name}, ${x.description}`}/><div><strong>{x.name}</strong><span>{x.description}</span></div></article>)}</div></div></section>
<section className="how"><div className="wrap section"><div className="sectionhead how-head"><div><span className="eyebrow"><Localized es="El intercambio, paso a paso" pt="A troca, passo a passo"/></span><h2><Localized es="Así de fácil" pt="É simples assim"/></h2><p><Localized es="Una comunidad hecha para viajar en serio." pt="Uma comunidade feita para viajar de verdade."/></p></div></div><div className="steps">{steps.map(({number,title,text,Icon})=><article key={number}><div className="step-illustration"><Icon/><div className="number">{number}</div></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="testimonials"><div className="wrap section"><div className="sectionhead"><div><span className="eyebrow"><Localized es="Historias de la comunidad" pt="Histórias da comunidade"/></span><h2><Localized es="Una forma más cercana de viajar" pt="Uma forma mais próxima de viajar"/></h2><p><Localized es="Lo que pasa cuando una casa abre la puerta a otra historia." pt="O que acontece quando uma casa abre a porta para outra história."/></p></div></div><div className="testimonial-grid"><article><Quote/><p><Localized es="‘En una semana conocimos Florianópolis como si viviéramos ahí. La anfitriona nos dejó sus lugares favoritos y todo fue muy simple.’" pt="‘Em uma semana conhecemos Florianópolis como se morássemos lá. A anfitriã nos deixou seus lugares favoritos e tudo foi muito simples.’"/></p><footer><b>Camila R.</b><span><Localized es="Buenos Aires · miembro Viajero" pt="Buenos Aires · membro Viajante"/></span></footer></article><article className="testimonial-featured"><Quote/><p><Localized es="‘Troca hizo posible usar mi casa cuando no estoy y conocer una cabaña increíble en Bariloche. El intercambio se sintió seguro desde el principio.’" pt="‘A Troca tornou possível usar minha casa quando não estou e conhecer uma cabana incrível em Bariloche. A troca pareceu segura desde o começo.’"/></p><footer><b>Joaquín M.</b><span><Localized es="Mendoza · anfitrión verificado" pt="Mendoza · anfitrião verificado"/></span></footer></article><article><Quote/><p><Localized es="‘Me gustó que no hace falta coordinar un intercambio exacto. Sumamos puntos hospedando y después elegimos cuándo viajar.’" pt="‘Gostei de não precisar combinar uma troca exata. Somamos pontos hospedando e depois escolhemos quando viajar.’"/></p><footer><b>Beatriz L.</b><span><Localized es="São Paulo · miembro Viajero" pt="São Paulo · membro Viajante"/></span></footer></article></div></div></section>
<section className="membership-explainer"><div className="wrap section"><div className="sectionhead"><div><span className="eyebrow">Tu membresía, en simple</span><h2>Cómo funciona Troca</h2><p>Una forma flexible de alojarte, compartir y aprovechar cada viaje.</p></div><Btn href="/register/plan" outline>Ver membresías</Btn></div><div className="program-grid">{program.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="program-note"><b>¿No tenés casa?</b> Con el Plan Base podés acceder a hoteles aliados y beneficios exclusivos de viaje.</div></div></section>
<section className="wrap section"><div className="saving"><div><span className="eyebrow" style={{color:'#dfcda9'}}>La cuenta es simple</span><h2>Tu membresía se paga sola.</h2></div><div><div className="big">Una noche con beneficio Troca puede amortizar toda tu membresía.</div><p>30 días de prueba gratis · Precios y beneficios disponibles al registrarte.</p></div></div></section>
<section className="wrap section"><div className="sectionhead"><div><h2>Hoteles con beneficios reales</h2><p>Diseñados para que cada escapada rinda más.</p></div><Btn href="/hotels" outline>Ver hoteles</Btn></div><div className="grid">{hotels.map(x=><HotelCard item={x} key={x.id}/>)}</div></section>
<section className="flight-section"><div className="wrap section"><div className="sectionhead"><div><span className="eyebrow">Beneficio Premium</span><h2>Vuelos para llegar más lejos</h2><p>Descuentos exclusivos en rutas seleccionadas para miembros Premium.</p></div><Btn href="/register/plan" outline>Conocer Premium</Btn></div><div className="flight-grid">{flightRoutes.map(x=><article className="flight-card" key={`${x[2]}-${x[3]}`}><span className="flight-badge">{x[5]}</span><div className="flight-route"><div><b>{x[2]}</b><small>{x[0]}</small></div><strong>→</strong><div><b>{x[3]}</b><small>{x[1]}</small></div></div><p>✈ {x[4]} · Beneficio para Plan Premium</p></article>)}</div><div className="flight-note">Los descuentos y la disponibilidad se confirman al solicitar la cotización. Próximamente, reserva integrada.</div></div></section>
<section className="wrap section"><div className="sectionhead"><div><h2>Elegí cómo querés viajar</h2><p>30 días gratis para empezar, sin tarjeta. El plan anual ofrece un ahorro claro frente al pago mes a mes.</p></div></div><PlanCards/><div className="plan-guide-wrap"><h2>Tu membresía, paso a paso</h2><MembershipGuide/></div></section>
<section className="points-section"><div className="wrap section"><PointsGuide/></div></section>
<section className="wrap section"><SecurityGuide/></section>
</main><Footer/></>}
