import Link from 'next/link';
export {Header, Footer} from './shell';
import { MapPin, Star, Users, ArrowRight, Heart, Plane, Home, CalendarDays, BadgeCheck } from 'lucide-react';
import { properties, hotels, plans } from '@/lib/data';
export const Btn=({href,children,outline=false}:{href:string,children:React.ReactNode,outline?:boolean})=><Link className={`btn ${outline?'outline':''}`} href={href}>{children}</Link>;
export function PropertyCard({item=properties[0]}:{item?:typeof properties[number]}){return <article className="card"><div className="image"><img src={item.image} alt={item.name}/><Heart size={17}/></div><div className="cardbody"><h3>{item.name}</h3><p><MapPin size={14}/>{item.city}</p><div className="cardbottom"><span><Users size={14}/>{item.guests} huéspedes</span><b>{item.points} pts/noche</b></div></div></article>}
export function HotelCard({item=hotels[0]}:{item?:typeof hotels[number]}){return <article className="card"><div className="image"><img src={item.image} alt={item.name}/><span className="benefit">{item.benefit}</span></div><div className="cardbody"><h3>{item.name}</h3><p><MapPin size={14}/>{item.city}</p><div className="cardbottom"><span><Star size={14}/>{item.rating}</span><Link href={`/hotels/${item.id}`}>Ver beneficio <ArrowRight size={14}/></Link></div></div></article>}
export function SearchBar(){return <div className="search"><span><MapPin/>Destino<input placeholder="¿A dónde querés viajar?"/></span><span><CalendarDays/>Fechas flexibles</span><Btn href="/properties">Buscar <ArrowRight size={16}/></Btn></div>}
export function PlanCards(){return <div className="plans">{plans.map(p=>{const saving=p.annualPrice===null?null:p.monthlyPrice*12-p.annualPrice;return <article key={p.id} className={`plan ${p.id==='viajero'?'featured':''}`}>{p.id==='viajero'&&<em>RECOMENDADO</em>}<h3>{p.name}</h3><p className="plan-description">{p.description}</p><div className="price-options"><div><small>Mensual</small><strong>USD {p.monthlyPrice}<i>/ mes</i></strong></div><div className="annual-price"><small>Anual</small>{p.annualPrice===null?<strong>A definir</strong>:<><strong>USD {p.annualPrice}<i>/ año</i></strong><b>Ahorrás USD {saving}</b></>}</div></div><ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul><Btn href={`/register?plan=${p.id}`} outline={p.id!=='viajero'}>Elegir {p.name}</Btn></article>})}</div>}
export function MembershipGuide(){return <div className="membership-guide"><article><span>01</span><h3>Elegí la frecuencia</h3><p>Podés empezar con pago mensual o elegir la membresía anual para ahorrar. Base y Viajero tienen precio anual definido; Premium anual se habilitará al lanzamiento.</p></article><article><span>02</span><h3>Publicá y verificá</h3><p>Con Viajero o Premium publicás tu casa, completás la verificación de identidad y definís las fechas disponibles.</p></article><article><span>03</span><h3>Solicitá un intercambio</h3><p>Cuando anfitrión y huésped confirman, se reservan los puntos de la estadía. El depósito virtual acompaña el intercambio.</p></article></div>}
export function PointsGuide(){return <div className="points-guide"><div><span className="eyebrow">Puntos Troca</span><h2>Una noche, una nueva posibilidad</h2><p>Los puntos representan el valor de una noche de alojamiento y se calculan según la demanda del destino y la temporada.</p></div><div className="points-rates"><article><b>0,5 pts</b><span>por noche</span><p>Demanda baja</p></article><article><b>1 pt</b><span>por noche</span><p>Demanda media</p></article><article><b>2 pts</b><span>por noche</span><p>Demanda alta</p></article></div><div className="points-notes"><p><b>Temporada:</b> alta +50% · baja −25%.</p><p><b>Al activar Viajero:</b> recibís 3 puntos de bienvenida.</p><p><b>Importante:</b> vencen al año, no se transfieren ni se canjean por dinero. Una cancelación tardía (menos de 15 días) descuenta 2 puntos.</p></div></div>}
export function SecurityGuide(){const safeguards=[['Identidad verificada','Para publicar e intercambiar una casa, el Plan Viajero requiere verificación de identidad.'],['Fotos de control','Cada intercambio incluye fotos obligatorias antes y después de la estadía. Si las imágenes del aviso no coinciden con la realidad, podés reportarlo antes de confirmar.'],['Depósito virtual','Durante el intercambio se mantiene un depósito virtual como respaldo ante daños o incumplimientos.'],['Reseñas ciegas','Anfitrión y huésped califican por separado: las reseñas se publican cuando ambas partes responden, para evitar presiones.']];return <div className="security-guide"><div className="security-intro"><span className="eyebrow">Confianza y seguridad</span><h2>Casas reales, intercambios cuidados.</h2><p>La comunidad funciona con información verificable y reglas claras. Si algo no coincide con la publicación, no tenés que avanzar.</p></div><div className="security-grid">{safeguards.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="security-note"><b>Antes de confirmar:</b> revisá las fotos, el perfil y las reseñas. Las fotos pre/post y el detalle de la estadía son la evidencia para resolver cualquier reporte.</p></div>}
export function PageHead({title,text,icon}:{title:string,text:string,icon?:React.ReactNode}){return <div className="pagehead">{icon}<div><h1>{title}</h1><p>{text}</p></div></div>}
export const Icons={Plane,Home,BadgeCheck};
